### PR TITLE
fix: remove stale popup buffers

### LINKED ISSUE #1124: bug: Editing leaves a lot of scratch buffers open
### Describe the bug

Whenever I edit my files with avante through selecting in visual mode and then editing inline, each prompt leaves a lot of open scratch buffers.
They contain avante stuff like `⠄ <C-s>: submit`

### To reproduce

1. open up any project
2. select a couple of lines in visual mode
3. edit them with avante (any prompt)
4. check `:ls!` to see unclosed scratch buffers
5. check `:buffer <id>` to see that scratch buffers contain avante stuff like `⠄ <C-s>: submit`
### Expected behavior

Avante should clean up after itself

### Installation method

Using nixvim:
```nix
   programs.nixvim.plugins.avante = {
      enable = true;
      settings = {
        provider = "copilot";
        mappings = {
          ask = "<leader>Aa";
          edit = "<leader>Ae";
          refresh = "<leader>Ar";
        };
      };
    };
```

### Environment

NVIM v0.10.3
Build type: Release
LuaJIT 2.1.1713773202
Run "nvim -V1 -v" for more info

Linux nixos 6.12.9 #1-NixOS SMP PREEMPT_DYNAMIC Thu Jan  9 12:33:55 UTC 2025 x86_64 GNU/Linux

### Repro

```lua

```

### PR DESCRIPTION
**Pull request by wvffle**
This PR aims to fix #1124

From my limited testing, it seems to cleanup the buffers now but please test it before merging.

### CODE REVIEW

File: lua/avante/sidebar.lua [hunk 1]
```diff
@@ -1029,17 +1029,16 @@ function Sidebar:apply(current_cursor)
...
       local spinner_frames = { "⣾", "⣽", "⣻", "⢿", "⡿", "⣟", "⣯", "⣷" }
       local spinner_idx = 1
       local loading_timer = nil
 
       local function update_loading_indicator()
-        if not loading_win or not api.nvim_win_is_valid(loading_win) then return end
+        if not loading_win or not loading_buf or not api.nvim_win_is_valid(loading_win) then return end
         spinner_idx = (spinner_idx % #spinner_frames) + 1
         local text = spinner_frames[spinner_idx] .. " Applying changes..."
-        api.nvim_buf_set_lines(loading_buf, 0, -1, false, { text })
```
Comment (yetone) [inline lua/avante/sidebar.lua:1042]: ‌‌Why delete this line?

Comment (wvffle) [reply lua/avante/sidebar.lua:1042]: Good catch! I must've deleted it by accident when adding checks for `loading_buf`
