### PR TITLE
fix: Gemini not reaching end state

### LINKED ISSUE #1024: bug: Gemini provider seems cannot reach complete state (Generation complete!)
### Describe the bug

Running Gemini with any prompt won't reach "Generation complete!". This result in log not saved

### To reproduce

```lua
:AvanteSwitchProvider gemini
:AvanteAsk
```

### Expected behavior

Prompt finished and log history saved.

### Installation method

Use lazy.nvim:
```lua
{
  "yetone/avante.nvim",
  event = "VeryLazy",
  lazy = false,
  version = false, -- set this if you want to always pull the latest change
  opts = {
    -- add any opts here
  },
  -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  build = "make",
  -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "stevearc/dressing.nvim",
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
  },
}
```

### Environment

```
NVIM v0.11.0-dev-4423+g3d3a99e69c-Homebrew
Build type: Release
LuaJIT 2.1.1732813678

Darwin 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec  6 19:01:59 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6000 arm64
```

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    -- add any other plugins here
  },
})
```

### PR DESCRIPTION
**Pull request by willheryanto**
Fixes #1024

## How to test?

Reference: https://github.com/google/generative-ai-docs/blob/main/site/en/gemini-api/docs/get-started/rest.ipynb

Running the following curl:

```
curl "https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:streamGenerateContent?alt=sse&key=$GEMINI_API_KEY" \
     -H 'Content-Type: application/json' \
     --no-buffer \
     -d '{ "contents":[{"parts":[{"text": "Write long a story about a magic backpack."}]}]}'
```

Response:

```
data: {"candidates": [{"content": {"parts": [{"text": "Hidden amidst a world of ordinary backpacks, there existed an extraordinary one, imbued with"}],"role": "model"},"index": 0,"safetyRatings": [{"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HATE_SPEECH","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HARASSMENT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_DANGEROUS_CONTENT","probability": "NEGLIGIBLE"}]}],"usageMetadata": {"promptTokenCount": 9,"candidatesTokenCount": 16,"totalTokenCount": 25},"modelVersion": "gemini-pro"}

data: {"candidates": [{"content": {"parts": [{"text": " a power that would forever alter the life of its young owner, Emily. Crafted from an ancient tapestry that shimmered under the moonlight, it held secrets that only"}],"role": "model"},"index": 0,"safetyRatings": [{"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HATE_SPEECH","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HARASSMENT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_DANGEROUS_CONTENT","probability": "NEGLIGIBLE"}]}],"usageMetadata": {"promptTokenCount": 9,"candidatesTokenCount": 48,"totalTokenCount": 57},"modelVersion": "gemini-pro"}

data: {"candidates": [{"content": {"parts": [{"text": " the deserving could unlock.\n\nAs fate would have it, Emily stumbled upon this enigmatic backpack at a dusty old thrift store. Its weathered exterior concealed an aura of mystery that drew her in like a moth to a flame. Little did she know that this seemingly innocuous object would become the catalyst for an extraordinary journey beyond her"}],"role": "model"},"index": 0,"safetyRatings": [{"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT","probability": "LOW"},{"category": "HARM_CATEGORY_HATE_SPEECH","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HARASSMENT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_DANGEROUS_CONTENT","probability": "NEGLIGIBLE"}]}],"usageMetadata": {"promptTokenCount": 9,"candidatesTokenCount": 112,"totalTokenCount": 121},"modelVersion": "gemini-pro"}

data: {"candidates": [{"content": {"parts": [{"text": " wildest dreams.\n\nWith each step she took, the backpack hummed with anticipation, its leather straps whispering secrets only Emily could hear. Its compartments, once empty, began to fill with an assortment of curious items—an ancient compass that always pointed towards adventure, a journal that recorded her thoughts and dreams, and a kaleidoscope that transformed the ordinary into the extraordinary.\n\nSoon, Emily realized that her ordinary life had been transformed into a grand tapestry woven with threads of magic and wonder. The backpack became her trusted companion, guiding her through hidden forests and forgotten ruins, opening doors to realms where imagination soared.\n\nOne fateful evening, as the"}],"role": "model"},"index": 0,"safetyRatings": [{"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HATE_SPEECH","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HARASSMENT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_DANGEROUS_CONTENT","probability": "NEGLIGIBLE"}]}],"usageMetadata": {"promptTokenCount": 9,"candidatesTokenCount": 241,"totalTokenCount": 250},"modelVersion": "gemini-pro"}

data: {"candidates": [{"content": {"parts": [{"text": " stars twinkled above, Emily found herself in a forgotten library, its shelves filled with dusty tomes and ancient scrolls. As she reached out to touch one of the books, the backpack sprang to life, its compartments opening to reveal a vast library of knowledge and forbidden spells.\n\nOverwhelmed by the revelation, Emily delved into the backpack's secrets, studying ancient languages and unlocking hidden powers. With each page she turned, her mind expanded with wisdom and her spirit grew stronger. The backpack became her oracle, guiding her choices and shaping her destiny.\n\nAs time went on, Emily's adventures became legendary. She traveled to distant lands, met extraordinary creatures, and faced challenges that tested her courage and resilience. The backpack was always by her side, a constant reminder of the endless possibilities that lay ahead.\n\nBut with great power came great responsibility. Emily understood that the backpack's secrets were not meant for selfish gain, but to be used for the greater good. She became a guardian of knowledge, sharing her wisdom with those who sought it and using her newfound abilities to protect the innocent.\n\nAnd so, Emily's journey continued, her magic backpack guiding her every step. Together, they became a symbol of hope and wonder, inspiring countless others to unlock their own"}],"role": "model"},"index": 0,"safetyRatings": [{"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HATE_SPEECH","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HARASSMENT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_DANGEROUS_CONTENT","probability": "NEGLIGIBLE"}]}],"usageMetadata": {"promptTokenCount": 9,"candidatesTokenCount": 497,"totalTokenCount": 506},"modelVersion": "gemini-pro"}

data: {"candidates": [{"content": {"parts": [{"text": " hidden potential and embark on extraordinary adventures of their own.\n\nAnd as the years turned into decades, the magic backpack became a cherished heirloom, passed down from generation to generation, a testament to the transformative power of imagination and the enduring bond between a girl and her extraordinary companion."}],"role": "model"},"finishReason": "STOP","index": 0,"safetyRatings": [{"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HATE_SPEECH","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_HARASSMENT","probability": "NEGLIGIBLE"},{"category": "HARM_CATEGORY_DANGEROUS_CONTENT","probability": "NEGLIGIBLE"}]}],"usageMetadata": {"promptTokenCount": 9,"candidatesTokenCount": 552,"totalTokenCount": 561},"modelVersion": "gemini-pro"}
```

### CODE REVIEW

**Comment by willheryanto** [comment]
Hi @yetone, please kindly help to review this when you have time. This fixes the issue that I raised.

Thanks!

File: lua/avante/providers/gemini.lua [hunk 1]
```diff
@@ -69,8 +69,13 @@ M.parse_response = function(data_stream, _, opts)
   if not ok then opts.on_complete(json) end
   if json.candidates then
     if #json.candidates > 0 then
-      opts.on_chunk(json.candidates[1].content.parts[1].text)
-    elseif json.candidates.finishReason and json.candidates.finishReason == "STOP" then
+      if json.candidates[1].finishReason and json.candidates[1].finishReason == "STOP" then
+        opts.on_chunk(json.candidates[1].content.parts[1].text)
+        vim.schedule(function() opts.on_complete(nil) end)
```
Comment (yetone) [inline lua/avante/providers/gemini.lua:74]: ‌There shouldn't be a need for `vim.schedule` here anymore, as I've already wrapped it in advance:

https://github.com/yetone/avante.nvim/blob/3ec847e3cbb08365b3205044275e6d7e28fcf01f/lua/avante/llm.lua#L399

Comment (willheryanto) [reply lua/avante/providers/gemini.lua]: Changed on https://github.com/willheryanto/avante.nvim/commit/aa9a3e246440b5ac96a496fa2d0698619ecca0f7
