### PR TITLE
fix: Adjust unset operation for api key name to after check for type

### LINKED ISSUE #2918: bug: Default Lazy lua install isnt able to detect claude key
### Describe the bug

Default Lazy lua install is unable to detect Claude Key,

### To reproduce

Using this exact Lazy lua https://github.com/yetone/avante.nvim?tab=readme-ov-file#installation
Then export AVANTE_ANTHROPIC_API_KEY=your-claude-api-key
or 
export ANTHROPIC_API_KEY=your-api-key

Retursn failure below

- Datetime: 2026-01-12 05:17:16
- Model:    claude/claude-sonnet-4-20250514

> Test

Error: {
  message = "x-api-key header is required",
  type = "authentication_error"
}

### Expected behavior

Expect the Claude to response to promp instead of x-api-key is required.

### Installation method

This is the exact as followed here https://github.com/yetone/avante.nvim?tab=readme-ov-file#installation
return {
  {
      "github/copilot.vim",
      lazy = false,
  },
  {
  "yetone/avante.nvim",
  -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
  -- ⚠️ must add this setting! ! !
  build = vim.fn.has("win32") ~= 0
      and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
      or "make",
  event = "VeryLazy",
  version = false, -- Never set this value to "*"! Never!
  ---@module 'avante'
  ---@type avante.Config
  opts = {
    -- add any opts here
    -- this file can contain specific instructions for your project
    instructions_file = "avante.md",
    -- for example
    provider = "claude",
    providers = {
      claude = {
        endpoint = "https://api.anthropic.com",
        model = "claude-sonnet-4-20250514",
        timeout = 30000, -- Timeout in milliseconds
        extra_request_body = {
          temperature = 0.75,
          max_tokens = 20480,
        },
      },
      moonshot = {
        endpoint = "https://api.moonshot.ai/v1",
        model = "kimi-k2-0711-preview",
        timeout = 30000, -- Timeout in milliseconds
        extra_request_body = {
          temperature = 0.75,
          max_tokens = 32768,
        },
      },
    },
  },
  dependencies = {
    "nvim-lua/plenary.nvim",
    "MunifTanjim/nui.nvim",
    --- The below dependencies are optional,
    "nvim-mini/mini.pick",           -- for file_selector provider mini.pick
    "nvim-telescope/telescope.nvim", -- for file_selector provider telescope
    "hrsh7th/nvim-cmp",              -- autocompletion for avante commands and mentions
    "ibhagwan/fzf-lua",              -- for file_selector provider fzf
    "stevearc/dressing.nvim",        -- for input provider dressing
    "folke/snacks.nvim",             -- for input provider snacks
    "nvim-tree/nvim-web-devicons",   -- or echasnovski/mini.icons
    "zbirenbaum/copilot.lua",        -- for providers='copilot'
    {
      -- support for image pasting
      "HakonHarnes/img-clip.nvim",
      event = "VeryLazy",
      opts = {
        -- recommended settings
        default = {
          embed_image_as_base64 = false,
          prompt_for_file_name = false,
          drag_and_drop = {
            insert_mode = true,
          },
          -- required for Windows users
          use_absolute_path = true,
        },
      },
    },
    {
      -- Make sure to set this up properly if you have lazy=true
      'MeanderingProgrammer/render-markdown.nvim',
      opts = {
        file_types = { "markdown", "Avante" },
      },
      ft = { "markdown", "Avante" },
    },
  },
  }
}

### Environment

PRETTY_NAME="Ubuntu 24.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"

NVIM v0.11.5

### Repro

```lua
Which lua file is this refering to?
```

### PR DESCRIPTION
**Pull request by jaljoue**
Fixes issue where api_key_name wasn't set for claude as it needed to be unset for the max subscription auth. Closes #2918, #2921

## Testing
Ran a query with an api key and the max auth key and got back the expected erorrs (my API account has no balance, but the correct key was used)
image

### CODE REVIEW

**Comment by ghosert** [comment]
was this bug introduced by your last merge to main? does my forked repo from main have the same issue?  https://github.com/ghosert/avante.nvim

**Comment by jaljoue** [comment]
@ghosert sorry yeah I thought that setting the key name when the auth_type was "api" would work but the parse_curl_headers function wasn't pulling the key properly. Leaving the key name alone fixed it since the oauth key would be grabbed from the `state` variable.

**Comment by jaljoue** [comment]
@yetone bump on this to fix API setting for claude

**Comment by arferreira** [comment]
@jaljoue nice man, do you know when it should be merged?

File: lua/avante/providers/claude.lua [hunk 1]
```diff
@@ -150,13 +150,13 @@ function M.setup()
   local auth_type = P[Config.provider].auth_type
 
   if auth_type == "api" then
-    M.api_key_name = "ANTRHOPIC_API_KEY"
```
Comment (sholland1) [inline lua/avante/providers/claude.lua]: Maybe the problem is that this is just spelled wrong:
ANT**RH**OPIC_API_KEY should be ANT**HR**OPIC_API_KEY
